version: '3.1'
services:
  # BackEnd Service - Spring Boot
  backend:
    image: gitlab.b46.it:4567/ticketnow/ticketnow/backend
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ticketnow?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root   
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  # FrontEnd Service - React
  frontend:
    image: gitlab.b46.it:4567/ticketnow/ticketnow/frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend
  # Database Service - MySQL
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ticketnow
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:   